# ----------------------------------------------------- 
# Install packages 
# ----------------------------------------------------- 

installer_packages=(
    "hyprland"
    "waybar"
    "rofi-wayland"
    "xdg-desktop-portal-hyprland"
    "qt5-wayland"
    "qt6-wayland"
    "hyprpaper"
    "hyprlock"
    "thunar"
    "ttf-font-awesome"
    "ttf-fira-sans" 
    "ttf-fira-code" 
    "ttf-firacode-nerd"
    "fuse2"
    "gtk4"
    "libadwaita"
    "jq"
    "python-gobject"
    "blueman"
    "brightnessctl"
    "jdk-openjdk"
    "pavucontrol"
    "grim"
    "slurp"
    "noto-fonts-cjk"
    "wqy-zenhei"
    "wqy-microhei"
    "fcitx5"
    "fcitx5-configtool"
    "fcitx5-chinese-addons"
    "fcitx5-gtk"
    "fcitx5-qt"
    "fzf"
    "mpv"
    "gamemode"
    "mangohud"
    "openssh"
    "cpupower"
    "tlp"
    "lib32-libx11"
    "lib32-libxcomposite"
    "lib32-mangohud"
    "linux-zen-headers"
    "xf86-video-intel"
    "neovim"
    "fastfetch"
    "pipewire"
    "pipewire-alsa"
    "pipewire-pulse"
    "wireplumber"
    "npm"
    "gdb"
    "vim"
    "flatpak"
    "ghostty"
    "yazi"
    "spotify-launcher"
    "wofi"
)

installer_yay=(
    "wlogout" 
    "minecraft-launcher"
    "zoom"
    "goverlay"
    "protonup-qt"
    "hyprshot"
    "swaync"
    "hypridle"
    "starship"
    "hyprpicker-git"
    "dunst"
    "nwg-look"
    "wf-recorder"
    "wlsunset"
    "btop"
    "viewnior"
    "ocs-url"
    "file-roller"
    "noto-fonts"
    "noto-fonts-cjk"
    "noto-fonts-emoji"
    "catppuccin-gtk-theme-macchiato"
    "catppuccin-gtk-theme-mocha"
    "papirus-icon-theme"
    "swaylock-effects-git"
    "kvantum"
    "kvantum-theme-catppuccin-git"
    "gst-plugin-pipewire"
)

_installPackages "${installer_packages[@]}";
_installPackagesYay "${installer_yay[@]}";

sudo pacman -S steam steam-native-runtime
