# ----------------------------------------------------- 
# Install packages 
# ----------------------------------------------------- 

installer_packages=(
    "hyprland"
    "waybar"
    "rofi-wayland"
    "alacritty"
    "thunar"
    "xdg-desktop-portal-hyprland"
    "qt5-wayland"
    "qt6-wayland"
    "hyprpaper"
    "hyprlock"
    "ttf-font-awesome"
    "neofetch"
    "ttf-fira-sans" 
    "ttf-fira-code" 
    "ttf-firacode-nerd"
    "fuse2"
    "gtk4"
    "libadwaita"
    "jq"
    "python-gobject"
    "blueman"
    "brightnessctl"
    "jdk-openjdk"
    "pavucontrol"
    "grim"
    "slurp"
    "noto-fonts-cjk"
    "wqy-zenhei"
    "wqy-microhei"
    "fcitx5"
    "fcitx5-configtool"
    "fcitx5-chinese-addons"
    "fcitx5-gtk"
    "fcitx5-qt"
    "fzf"
    "mpv"
    "gamemode"
    "mangohud"
    "wine-staging"
    "vulkan-intel"
    "lib32-vulkan-intel"
    "openssh"
    "cpupower"
    "libva-intel-driver"
    "intel-media-driver"
    "tlp"
    "lib32-libx11"
    "lib32-libxcomposite"
    "lib32-mangohud"
    "linux-zen-headers"
    "xf86-video-intel"
    "neovim"
    "fastfetch"
    "pipewire"
    "pipewire-alsa"
    "pipewire-pulse"
    "wireplumber"
    "npm"
    "gdb"
    "vim"
    "flatpak"
)

installer_yay=(
    "wlogout" 
    "minecraft-launcher"
    "zen-browser"
    "zoom"
    "goverlay"
    "protonup-qt"
    "hyprshot"
    "swaync"
    "hypridle"
    "starship"
    "ast-grep"
)

_installPackages "${installer_packages[@]}";
_installPackagesYay "${installer_yay[@]}";

sudo pacman -S steam steam-native-runtime
